### ISSUE TITLE
Errors occurred while creating driver package - Lenovo

### ISSUE THREAD

**Issue by pcam23** [maurice-daly/DriverAutomationTool#112]
Error: The SMS Provider reported an error. System.Management.ManagementException: Generic failure 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.Put(PutOptions options)
   at Microsoft.ConfigurationManagement.ManagementProvider.WqlQueryEngine.WqlResultObject.Put(ReportProgress progressReport)

**Comment by tcoliver** [comment]
I am having the same issue. I can create Standard Packages without a problem; however, I get the exact error above any time I try to create a Driver Package. The error occurs at the start of the package creation process, just after the driver has been downloaded and extracted. Below is the relevant portion of the logs (with edits to remove usernames and drive paths). 

```
<![LOG[ConfigMgr: Creating driver package for Dell Optiplex 5080 (Version A01)]LOG]!><time="11:41:35.383 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="1" thread="8780" file="">
<![LOG[ConfigMgr: Driver package name is Dell Optiplex 5080 - Windows 10 x64]LOG]!><time="11:41:35.395 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="1" thread="8780" file="">
<![LOG[ConfigMgr: Path to drivers is \\path\to\dir\Drivers\Packages\Dell\Optiplex 5080-Windows10-x64-A01\DriverPkg\]LOG]!><time="11:41:35.407 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="1" thread="8780" file="">
<![LOG[ConfigMgr: Creating driver package]LOG]!><time="11:41:35.419 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="1" thread="8780" file="">
<![LOG[======== Errors(s) Occurred ========]LOG]!><time="11:41:35.747 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="3" thread="8780" file="">
<![LOG[Error: The SMS Provider reported an error. System.Management.ManagementException: Generic failure 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.Put(PutOptions options)
   at Microsoft.ConfigurationManagement.ManagementProvider.WqlQueryEngine.WqlResultObject.Put(ReportProgress progressReport)]LOG]!><time="11:41:35.762 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="3" thread="8780" file="">
<![LOG[ ]LOG]!><time="11:41:35.780 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="3" thread="8780" file="">
<![LOG[ConfigMgr: Running driver import process (this might take several minutes)]LOG]!><time="11:41:35.792 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="1" thread="8780" file="">
<![LOG[======== Errors(s) Occurred ========]LOG]!><time="11:41:35.804 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="3" thread="8780" file="">
<![LOG[Error: Errors occurred while creating driver package]LOG]!><time="11:41:35.817 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="3" thread="8780" file="">
<![LOG[ ]LOG]!><time="11:41:35.829 -300" date="10-15-2020" component="DriverAutomationTool" context="{{MYUSERNAME}}" type="3" thread="8780" file="">
```

Version: 6.4.9
Build Date: 2020-09-14

**Comment by DatsiK96** [comment]
I'm getting this exact error. No other information is presented in the logs.

DriverCatalog.log doesn't have anything for the driver package creation.

I am able to get some of the driver packs to be created, but not all of them. A majority don't work for some reason.

I can manually create driver packs... I wish I could see the powershell command it's trying to utilize...

Using the same version as above:
Version: 6.4.9
Build Date: 2020-09-14
SCCM is 2010, it didn't work with 1906 either.

**Comment by cossin08** [comment]
Hello,

Have you ever found a solution for this? I try with version 6.4.9 and 6.5.0 BETA. SCCM build is 2010.

Thanks

**Comment by tcoliver** [comment]
> Hello,
> 
> Have you ever found a solution for this? I try with version 6.4.9 and 6.5.0 BETA. SCCM build is 2010.
> 
> Thanks

We have not. Currently it's still an issue. Luckily, with the pandemic new machine purchases have been minimal, so we have resorted to running Dell Command | Update after imaging to ensure the drivers are installed.

**Comment by AlkHacNar** [comment]
Is the package created in sccm, do you see it in the console? if yes, delete it and the package path destination folder. Then look under software library/ operation systems/ drivers if some of them have a content source path (must select the collumn), which is not available any more. I had this problem with some lenovo drivers. just delete them and let DAT import again.
